# 第 12 章 朴素贝叶斯

**朴素贝叶斯**（naive Bayes）是基于贝叶斯定理发展起来的非常简单而又有效的概率机器学习方法，可用于各种分类任务。

朴素贝叶斯模型易于构建，没有复杂的迭代参数估计，可以很容易编码，并且能够非常快地预测。这使得它对于非常大的数据集特别有用。尽管简单，但朴素贝叶斯分类器通常表现出色，并且由于它通常优于更复杂的分类方法而被广泛使用。

## 12.1 基本概念

### 12.1.1 类条件独立性假定

如果因变量有 $K$ 类，为 $c_1,c_2,\ldots,c_K$，朴素贝叶斯假定在给定 $c_k$（$k=1,2,\ldots,K$）的条件下自变量 $\boldsymbol{x}=(x_1,x_2,\ldots,x_n)$ 都是独立的，这称为**类条件独立性**（class conditional independence）。这种独立性假定给了该方法"朴素"（或天真，naive）的帽子，它意味着改变一个变量的值，不直接影响或改变算法中使用的任何其他变量的值。

朴素贝叶斯方法通常在给定类别（比如 $c_k$）之后假定了它们的条件分布 $p(x_i\mid c_k)$ 的类型，比如正态分布、多项分布或 Bernoulli 分布等。

朴素贝叶斯的目的就是要计算在给定数据 $\boldsymbol{x}$ 的条件下属于类 $c_k$ 的概率，即后验概率 $p(c_k\mid\boldsymbol{x})$，并且求使后验概率最大的类 $c_k$。

根据贝叶斯定理，后验分布（给定数据 $\boldsymbol{x}$ 的条件下属于类 $c_k$ 的概率）

$$
p(c_k\mid\boldsymbol{x}) = \frac{p(c_k)p(\boldsymbol{x}\mid c_k)}{p(\boldsymbol{x})} \tag{12.1.1}
$$

$$
\propto p(c_k)p(\boldsymbol{x}\mid c_k) = p(c_k)p(x_1,x_2,\ldots,x_n\mid c_k) \tag{12.1.2}
$$

$$
= p(c_k)p(x_1\mid c_k)p(x_2\mid c_k)\cdots p(x_n\mid c_k) = p(c_k)\prod_{i=1}^n p(x_i\mid c_k) \tag{12.1.3}
$$

其中，式(12.1.1)是贝叶斯定理，式(12.1.2)是因为分母的概率 $p(\boldsymbol{x})$ 与我们关心的类没有关系（这里符号 $\propto$ 是"成比例"的意思），式(12.1.3)是因为假定了观测值 $x_1,x_2,\ldots,x_n$ 在给定了 $c_k$ 的条件下独立。

有了上面的式子及假定的 $p(x_i\mid c_k)$ 的条件分布，给定数据 $x_1,x_2,\ldots,x_n$ 之后，我们就可以寻求使得 $p(c_k)\prod_{i=1}^n p(x_i\mid c_k)$ 最大的类 $c_k$。

### 12.1.2 朴素贝叶斯分类器类型

如果没有具体的概率分布则无法计算。上面说到，给定类别（比如 $c_k$）之后需要假定它们的条件分布 $p(x_i\mid c_k)$ 的类型，比如正态分布、多项分布或 Bernoulli 分布等。

- **多项朴素贝叶斯**：可用于属性分类的问题。比如一个评论是正面、负面还是中性等；一个文档是属于体育、科技、民生、新闻等。预测变量多为某种特征的频数
- **Bernoulli 朴素贝叶斯**：预测变量通常是二分变量或布尔变量
- **高斯朴素贝叶斯**：当预测变量是连续的而非离散的时，通常假设这些值有正态总体

虽然在上面做了一些诸如独立性或分布等假定，实际上这些假定并不一定满足，但这个方法却产生很精确的分类。因此从某种意义上说，朴素贝叶斯方法仅仅是借用了贝叶斯定理及后验分布的思想来解释其方法的根据。

## 12.2 朴素贝叶斯方法分类数值例子

**例 12.1**（`indian_diabetes.csv`）该数据集描述了皮马印第安人的医疗记录以及每个患者是否在多年内患有糖尿病。具体变量描述如下：`preg`（怀孕的次数），`plas`（口服葡萄糖耐量试验中的2小时血浆葡萄糖浓度），`pres`（舒张压，mmHg），`skin`（肱三头肌皮肤褶皱厚度，mm），`test`（2小时血清胰岛素，$\mu$U/ml），`bmi`（体重指数，体重kg/身高$m^2$），`pedi`（糖尿病谱系功能），`age`（年龄，岁），`class`（类，1：糖尿病检测阳性，0：