# 第 13 章 贝叶斯网络

本章的主要内容来自吴喜之所著的教材《复杂数据统计方法——基于R的应用》（第三版）（中国人民大学出版社，2015）的第12章。

## 13.1 概述

### 13.1.1 基本概念

属于概率图形（probabilistic graphical models, GM）族的网络模型**贝叶斯网络**（Bayesian networks, BN）包括图理论、概率论、计算机科学及统计的概念，是多变量概率分布的一种概率图模型。

贝叶斯网络包含**有向无回路图**（directed acyclic graph, DAG）。DAG 是由**节点**（node）或**顶点**（vertex）和**有向边**或**有向弧**组成的。无回路意味着没有节点是它自己的祖先或后代，也就是顺着箭头不会经过已经走过的节点。DAG 的每个节点都对应于一个变量，箭头代表变量之间的相依关系。每个箭头的终点称为"子节点"（child），起点称为"父节点"（parent）。和图模型类似，没有父节点的节点称为**根节点**（root node），没有子节点的节点称为**叶节点**（leaf node），其他节点称为**中间节点**（intermediate node）。每个变量都附有给定其父节点的（条件）局部概率，因此贝叶斯网络也称为概率有向无回路图模型（probabilistic directed acyclic graphical model），这就区别于其他具有DAG的图模型。

贝叶斯网络的每个变量 $x_i$ 在一个有向无回路图中表示为节点（或称顶点）；概率分布 $p(x_1,x_2,\ldots,x_N)$ 以因子分解的形式表示如下：

$$
p(x_1,x_2,\ldots,x_N) = \prod_{i=1}^{M} p(\boldsymbol{x}_i\mid\Pi_{x_i}) \tag{13.1.1}
$$

这里 $\Pi_{x_i}$ 是图中 $x_i$ 父节点的集合。这个表达式显示了贝叶斯网络满足因果马尔可夫假定，即每个点的概率在给定其父节点时独立于其他祖先，表达式(13.1.1)还使得一个原本非常烦琐的联合分布大大简化。贝叶斯网络被下面二者完全确定：

1. **图结构**，即图中的有向弧（或有向边）
2. 对每个变量 $x_i$ 的**条件概率表**（conditional probability table, CPT）

当一个贝叶斯网络被确定之后，就可以通过式(13.1.1)计算想要的任何条件概率，这可以直接用手算（比如对下面例13.1的简单情况），当然，通常是用计算机软件实现。

贝叶斯网络非常便于表示概率因果关系系统。一方面，通过从一个节点到另一个节点（比如图13.1.1中的 $C$ 到 $R$）添加有向边并适当地设置概率，就可以很容易地在网络中确立"$C$ 如何经常导致 $R$"的事实；另一方面，如果 $C$ 对 $B$ 没有因果影响，它们之间就不会有一个有向边。

贝叶斯网络广泛应用于统计、机器学习、人工智能等领域。贝叶斯网络在数学上严格而且易于理解。虽然箭头代表变量间直接的因果关系，但推理能够作用于任何方向（无论有没有箭头）。

贝叶斯网络不像完全主观建造而又很难更新或修改的结构方程模型，它根据数据中变量之间的相关性来构建图中的变量联系，同时也可以加上主观的介入。因此，贝叶斯网络从某种意义上来说比图模型更加客观，与数据所反映的现实世界的关系也更加密切。

### 13.1.2 贝叶斯网络的难点及优缺点

贝叶斯网络中有哪些变量（节点）、它们之间的关系（那些有向边或有向弧）以及有关的条件概率表（CPT）实际上是很难事先知道的，这些必须根据数据来获得，这就是贝叶斯网络最核心也是充斥着难点的地方。

#### 1. 优点

- 适用于较小的和不完全的数据集
- 能够通过数据学习网络结构和各种条件概率
- 可结合不同来源的信息，包括主观的、怀疑的以及证据确凿的信息
- 明白地处理不确定性，并支持决策系统
- 所有结构都以解析的形式描述，一旦结构的学习过程完成，可以很快得到想要的结论

#### 2. 缺点

- 选择先验分布不很容易
- 对于连续变量有困难，通常需要离散化，这有利有弊
- 把专家知识构造进贝叶斯网络有各种困难，包括概率的确定
- 做完全的贝叶斯学习过程极其花费计算资源，即使在网络结构已知的情况下仍然不易
- 对于高维数据贝叶斯网络表现不佳
- 贝叶斯网络可能不易解释，特别是不同部分效果的区分
- 对于并非不常见的循环的关系，会很困难（可能需要非指向的图模型，诸如马尔可夫随机域）

### 13.1.3 贝叶斯网络的一个简单例子

**例 13.1** 图13.1.1是一个简单的贝叶斯网络例子。$C$ 表示通常的感冒，$R$ 表示流鼻涕，$H$ 表示头疼，$B$ 表示接触过有禽流感的家禽，$A$ 是禽流感，$N$ 是一般抗生素无效。左图为贝叶斯网络，右图为每个变量为真（T，用哑元1代表）及为伪（F，哑元0代表）的概率及条件概率。