# 隐马尔可夫模型

## 14.1 概述

**隐马尔可夫模型**（hidden Markov model, HMM）是具有不可观察（即隐藏）状态的马尔可夫模型。它可以表示为最简单的动态贝叶斯网络。HMM 背后的数学最初是由 Baum and Petrie (1966) 提出的。HMM 与早期 Stratonovich (1960) 关于最优非线性滤波问题的研究密切相关。

在更简单的马尔可夫模型（如马尔可夫链）中，状态对于观察者是直接可见的，因此状态转移概率是唯一的参数，而在隐马尔可夫模型中，可观测的仅仅是取决于不可观测状态的显示。这些显示的数据给出了关于状态的信息而不是状态本身。

隐马尔可夫模型可以认为是混合模型的推广，这里控制混合分量的隐变量不是独立的而是由马尔可夫模型联系的，也称为**依赖混合模型**（dependent mixture model）。HMM 强化学习和瞬时模式识别等在诸如心理学、经济学、遗传学及各种社会科学领域中有广泛的应用。

举例来说，我们可以看见下雨（Rain）、阴天（Cloudy）和不下雨（Dry），这是可观测的状况，相应的高空气压有高（High）、低（Low）之分，这是人们不可观测的状态。假定高空状态是个马尔可夫链，有状态转移概率矩阵：

$$
\boldsymbol{A} = \begin{bmatrix} 0.7 & 0.3 \\ 0.2 & 0.8 \end{bmatrix}
$$

或者

|  | High | Low |
|---|---|---|
| **High** | $P(\text{High}\mid\text{High})=0.70$ | $P(\text{Low}\mid\text{High})=0.30$ |
| **Low** | $P(\text{High}\mid\text{Low})=0.20$ | $P(\text{Low}\mid\text{Low})=0.80$ |

对于这个马尔可夫链，可假定有一个初始概率：

$$
\boldsymbol{\pi} = \begin{bmatrix} 0.6 \\ 0.4 \end{bmatrix}
$$

或者

$$
P(\text{High})=0.6;\quad P(\text{Low})=0.4
$$


这样，通过 $n$ 次转移之后的各个状态的概率为 $\boldsymbol{A}^n\boldsymbol{\pi}$。

从不可见的状态到可观测的状态会有一个**发送**（emission）概率转移矩阵：

$$
\boldsymbol{B} = \begin{bmatrix} 0.6 & 0.3 & 0.1 \\ 0.2 & 0.2 & 0.6 \end{bmatrix}
$$

或者

|  | Dry | Cloudy | Rain |
|---|---|---|---|
| **High** | $P(\text{Dry}\mid\text{High})=0.60$ | $P(\text{Cloudy}\mid\text{High})=0.30$ | $P(\text{Rain}\mid\text{High})=0.10$ |
| **Low** | $P(\text{Dry}\mid\text{Low})=0.20$ | $P(\text{Cloudy}\mid\text{Low})=0.20$ | $P(\text{Rain}\mid\text{Low})=0.60$ |

这时，如果 $\boldsymbol{\pi},\boldsymbol{A},\boldsymbol{B}$ 都已知，那么在 $n$ 次转移之后的可观测状态的概率为 $\boldsymbol{B}^\top\boldsymbol{A}^n\boldsymbol{\pi}$。**当然，在现实世界，这些概率并不一定都是已知的。** 图14.1.1为马尔可夫链的隐状态 $\{S_t\}$、可观测状态 $\{O_t\}$（$t=1,2,\ldots,T$）通过转移概率矩阵 $\boldsymbol{A}$ 及 $\boldsymbol{B}$ 导出的关系示意图。

```{{mermaid}}
flowchart LR
    S1((S1)) -->|A| S2((S2)) -->|A| S3((...)) -->|A| ST((ST))
    S1 -->|B| O1[O1]
    S2 -->|B| O2[O2]
    S3 -->|B| O3[...]
    ST -->|B| OT[OT]
```

图 14.1.1 隐状态 $\{S_t\}$、可观测状态 $\{O_t\}$（$t=1,2,\ldots,T$）通过转移概率矩阵 $\boldsymbol{A}$ 及 $\boldsymbol{B}$ 导出的关系示意图

下面定义一些符号：

- $\boldsymbol{S}=\{S_t\}\ (t=1,2,\ldots,T)$：隐马尔可夫过程
- $T$：观测序列长度
- $n$：模型中状态个数
- $m$：可观测的值的个数
- $\boldsymbol{s}=\{s_i\}$：有 $n$ 个元素的状态空间，即隐马尔可夫过程的不同的状态
- $\boldsymbol{V}=\{v_1,v_2,\ldots,v_m\}$：可能观测到的值的集合
- $\boldsymbol{A}=\{a_{ij}\}$：$(n\times n)$ 状态转移概率矩阵，有可能是某协变量 $\boldsymbol{z}_t$ 的函数 $a_{ij}(\boldsymbol{z}_t)$
- $\boldsymbol{B}$：$(n\times m)$ 发送转移概率矩阵，其元素有时记为 $\{b_{S_i}(O_j)\}$。它有可能是某协变量 $\boldsymbol{z}_t$ 的函数

- $\boldsymbol{\pi}=\{\pi_i\}$：状态的初始分布的 $(n)$ 维向量，有可能是某协变量 $\boldsymbol{z}_t$ 的函数 $\pi_i(\boldsymbol{z}_t)$
- $\boldsymbol{O}=\{O_t\}$：观测值序列

对于前面天气和气压的例子，如果我们的观测值为

$$
\boldsymbol{O} = (\text{Rain}, \text{Rain}, \text{Cloudy}, \text{Dry})
$$

除了前面给出的 $\boldsymbol{\pi},\boldsymbol{A},\boldsymbol{B}$ 之外，对于该例有

$$
T=4,\quad n=2,\quad \boldsymbol{s}=\{\text{High},\text{Low}\},\quad m=3,\quad \boldsymbol{V}=\{\text{Rain},\text{Cloudy},\text{Dry}\}
$$

对于任意状态序列 $s_i\in\boldsymbol{s}$（$i=1,\ldots,n$），不可观测状态的马尔可夫性定义为

$$
P(S_n=s_n\mid S_1=s_1,\ldots,S_{n-1}=s_{n-1}) = P(S_n=s_n\mid S_{n-1}=s_{n-1})
$$

隐马尔可夫模型（HMM）由三个概率表示为

$$
M = (\boldsymbol{A},\boldsymbol{B},\boldsymbol{\pi})
$$

## 14.2 HMM 的三个主要问题

**(1) 评估问题**：对于 HMM 问题 $M=(\boldsymbol{A},\boldsymbol{B},\boldsymbol{\pi})$ 和观测序列 $\boldsymbol{O}=\{O_i\}$，找到产生 $\{O_i\}$ 序列的概率 $P(\boldsymbol{O}\mid M)$。方法是得到 $\boldsymbol{O}$ 相对于给定模型 $M$ 的得分。

**(2) 解码问题**：对于 HMM 问题 $M=(\boldsymbol{A},\boldsymbol{B},\boldsymbol{\pi})$ 和观测序列 $\boldsymbol{O}=\{O_i\}$，找到隐马尔可夫过程的最佳状态序列，也就是最可能产生 $\boldsymbol{O}$ 的隐马尔可夫过程。

**(3) 学习问题**：给定观察序列 $\boldsymbol{O}$ 与维度 $n$ 和 $m$，找到最可能产生 $\boldsymbol{O}$ 的概率模型 $M=(\boldsymbol{A},\boldsymbol{B},\boldsymbol{\pi})$，即训练模型以最佳地拟合观察到的数据。这也可视为在参数 $\boldsymbol{A},\boldsymbol{B},\boldsymbol{\pi}$ 的（离散）空间上的登山法。

下面对这三个问题作出说明。

### 14.2.1 评估问题

观测序列 $\boldsymbol{O}=\{O_i\}$，找到产生 $\{O_i\}$ 序列的概率 $P(\boldsymbol{O}\mid M)$。我们有

$$
P(\boldsymbol{O}\mid M) = \sum_{S\in\boldsymbol{s}} P(\boldsymbol{O}\mid S,M)P(S\mid M)
$$

$$
= \sum_{S\in\boldsymbol{s}} \pi_{S_1}b_{S_1}(O_1)\cdot a_{S_1,S_2}b_{S_2}(O_2)\cdot a_{S_2,S_3}b_{S_3}(O_3)\cdots a_{S_{T-1},S_T}b_{S_T}(O_T) \tag{14.2.1}
$$

然而，这种直接计算通常是不可行的，因为它需要乘大约 $2\times T\times n^T$ 次。但存在能够达到同样结果的更加有效的算法。下面介绍具体的算法。

